#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 15 11:23:28 KST 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sel_case_behav -key {Behavioral:sim_1:Functional:sel_case} -tclbatch sel_case.tcl -view /home/npl/Learning_Vivado/seq_lab/d_ff_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/edge_det_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/sr8_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/cnt_pls8_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/cnt_priority_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/sel_if_behav.wcfg -log simulate.log"
xsim sel_case_behav -key {Behavioral:sim_1:Functional:sel_case} -tclbatch sel_case.tcl -view /home/npl/Learning_Vivado/seq_lab/d_ff_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/edge_det_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/sr8_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/cnt_pls8_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/cnt_priority_behav.wcfg -view /home/npl/Learning_Vivado/seq_lab/sel_if_behav.wcfg -log simulate.log

