#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 08 18:41:12 KST 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim gate2_behav -key {Behavioral:sim_1:Functional:gate2} -tclbatch gate2.tcl -view /home/npl/Learning_Vivado/comp_lab/and2_behav.wcfg -view /home/npl/Learning_Vivado/comp_lab/gate2_behav.wcfg -log simulate.log"
xsim gate2_behav -key {Behavioral:sim_1:Functional:gate2} -tclbatch gate2.tcl -view /home/npl/Learning_Vivado/comp_lab/and2_behav.wcfg -view /home/npl/Learning_Vivado/comp_lab/gate2_behav.wcfg -log simulate.log

